import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./layout/Header";
import Footer from "./layout/Footer";
import FooterSpacer from "./layout/FooterSpacer";
import Script from "next/script";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full antialiased">
			<body className="min-h-full flex flex-col">
				<Script
					src="https://kit.fontawesome.com/0e7d01b6b6.js"
					crossOrigin="anonymous"
					strategy="afterInteractive"
				/>
				<Header />
				{children}
				<FooterSpacer />
				<Footer />
			</body>
		</html>
	);
}
